version: '3'

services:
  postgres:
    image: 'postgres:13'
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - '5432:5432'
    volumes:
      - ./pgdata:/var/lib/postgresql/data
  ecparents:
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: ${POSTGRES_HOST}
      NODE_ENV: ${NODE_ENV}
      # POSTGRES_DB: todolist
      PORT: 8080
      JWT_SECRET: ${JWT_SECRET}
    platform: linux/amd64
    depends_on:
      - postgres
    build:
      context: ./
      dockerfile: ./Dockerfile
    image: 'michaellinlin/ecparents:latest'
    ports:
      - '8080:8080'
